### ISSUE TITLE
instance crush when method is not valid?

### ISSUE THREAD

**Issue by jmikerq** [chameleonbr/node-red-contrib-soap#6]
This is the info when I enter invalid method, say for example, 'test' in the config tag, and then this throws back and crush the node-red instance:

17 Oct 21:16:15 - [red] Uncaught Exception:
17 Oct 21:16:15 - TypeError: client[node.method] is not a function
at /user/node_modules/node-red-contrib-soap-nothrow/soap-node.js:41:40
at /user/node_modules/node-red-contrib-soap-nothrow/node_modules/soap/lib/soap.js:50:5
at null.callback (/user/node_modules/node-red-contrib-soap-nothrow/node_modules/soap/lib/soap.js:37:7)
at /user/node_modules/node-red-contrib-soap-nothrow/node_modules/soap/lib/wsdl.js:1076:12
at WSDL._processNextInclude (/user/node_modules/node-red-contrib-soap-nothrow/node_modules/soap/lib/wsdl.js:1133:12)
at WSDL.processIncludes (/user/node_modules/node-red-contrib-soap-nothrow/node_modules/soap/lib/wsdl.js:1166:8)
at /user/node_modules/node-red-contrib-soap-nothrow/node_modules/soap/lib/wsdl.js:1031:10
at nextTickCallbackWith0Args (node.js:420:9)
at process._tickCallback (node.js:349:13)

**Comment by giuriagiuria** [comment]
Dear Team
I'm also facing the same issue ... but to be honest I do not know which kind of value I have to put as COMMAND ... but it looks like to be mandatory ...

Kindly ask you to help in understanding how to proceed to successfully use this important node.
Thanks for your support.
Raul

**Comment by chameleonbr** [comment]
Hello @jmikerq I see your effort to make this repo ok. Unfortunately I am now focused on other projects, if you want and can collaborate I would be grateful.

**Comment by jmikerq** [comment]
Thank you @chameleonbr. I will merge my changes to this repo.

**Comment by jmikerq** [comment]
@chameleonbr can you give me a write permission, so I can maintain without doing a pull request? Also, just realize that it would still need your permission to publish the updated version onto npm

**Comment by chameleonbr** [comment]
Ok, how can I change this in NPM?

**Comment by chameleonbr** [comment]
I added sensetecnic to the contributors.

**Comment by jmikerq** [comment]
thanks @chameleonbr I will try to see if I can publish that after merging
